# -*- coding: utf-8 -*-
"""imdb_scraper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117QqKwzUa09ZSYsVYJ2-K7aZtyqM7yvd
"""

# imdb_scraper.py
# ---------------------------------------------------------
# IMDb Movie Scraper + "Where to Watch" Finder (Bonus Task)
# Author: Mohit Kumar Gupta
# ---------------------------------------------------------

import requests
from bs4 import BeautifulSoup
import json
import time
from urllib.parse import quote_plus


# ---------------------------------------------------------
# TASK 1: IMDb Movie Scraper (via OMDb API)
# ---------------------------------------------------------
def get_imdb_movies(genre, language, keyword):
    """
    Fetch top 10 movies from OMDb API (IMDb data) based on a keyword.
    """
    API_KEY = "26d56479"
    url = f"http://www.omdbapi.com/?apikey={API_KEY}&s={keyword}&type=movie"

    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"⚠️ API request failed: {e}")
        return []

    data = response.json()
    if "Search" not in data:
        return []

    movies = []
    for item in data["Search"][:10]:
        movie_id = item["imdbID"]
        details_url = f"http://www.omdbapi.com/?apikey={API_KEY}&i={movie_id}&plot=short"
        details = requests.get(details_url).json()

        movies.append({
            "Movie Name": details.get("Title", "N/A"),
            "Release Date": details.get("Released", "N/A"),
            "IMDb Rating": details.get("imdbRating", "N/A"),
            "Director": details.get("Director", "N/A"),
            "Main Cast": details.get("Actors", "N/A").split(", ")[:5],
            "Description": details.get("Plot", "N/A")
        })

    return movies


# ---------------------------------------------------------
# TASK 2: Bonus Task - Where to Watch Finder
# ---------------------------------------------------------
def find_where_to_watch(movie_name):
    """
    Bonus Task: Find where to watch using both Google and JustWatch fallbacks.
    Works even if one of them is blocked.
    """
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    platforms = set()

    # --- 1️⃣ Google Search Fallback ---
    try:
        query = f"{movie_name} watch online India Netflix Amazon Hotstar JioCinema"
        url = f"https://www.google.com/search?q={quote_plus(query)}"
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        text = soup.get_text().lower()

        possible_platforms = [
            "netflix", "amazon prime", "prime video", "jiocinema",
            "hotstar", "disney+", "zee5", "sonyliv", "mx player"
        ]
        for p in possible_platforms:
            if p in text:
                platforms.add(p.capitalize())

    except requests.exceptions.RequestException:
        pass

    # --- 2️⃣ JustWatch Fallback ---
    try:
        jw_url = f"https://www.justwatch.com/in/search?q={quote_plus(movie_name)}"
        jw_response = requests.get(jw_url, headers=headers, timeout=10)
        soup = BeautifulSoup(jw_response.text, "html.parser")
        text = soup.get_text().lower()
        for p in ["netflix", "amazon", "hotstar", "disney", "jiocinema", "zee5", "sonyliv", "mx"]:
            if p in text:
                platforms.add(p.capitalize())
    except requests.exceptions.RequestException:
        pass

    return list(platforms) if platforms else ["Not found"]



# ---------------------------------------------------------
# MAIN EXECUTION
# ---------------------------------------------------------
if __name__ == "__main__":
    print("=== 🎬 IMDb Movie Scraper ===")
    genre = input("Enter Genre (e.g., Drama, Sci-Fi): ")
    language = input("Enter Language (e.g., English, Hindi): ")
    keyword = input("Enter Keyword (e.g., love, space, mystery): ")

    print("\n🔍 Fetching top movies from IMDb (via OMDb API)...\n")
    movies = get_imdb_movies(genre, language, keyword)

    if not movies:
        print("⚠️ No movies found. Try changing your genre or keyword.")
    else:
        print(json.dumps(movies, indent=4, ensure_ascii=False))

    print("\n=== 🎥 Finding Where to Watch (Bonus Task) ===")
    for movie in movies:
        print(f"\n🔸 Checking: {movie['Movie Name']} ...")
        time.sleep(2)
        platforms = find_where_to_watch(movie['Movie Name'])
        print(f"👉 {movie['Movie Name']} -> Available on: {', '.join(platforms)}")

    print("\n✅ Task Completed Successfully!")